### ISSUE TITLE
[client/server] [Bare Minimum] - 계획 세우기

### ISSUE THREAD

**Issue by lovelysi0113** [lovelysi0113/Side_Project_Trollo#1]
### ISSUE
- Group: `client`, `server`
- Type: `plan`
- Detail: 사이트 프로젝트 계획 세우기

### TODO
1. [ ] 어떤 부분을 리펙토링할 것인가?
2. [ ] 어떤 언어로 리펙토링할 것인가?
3. [ ] 어느 수준까지 리펙토링할 것인가?
4. [ ] 계획 정리해서 이슈카드로 만들어놓기
